---

# THIS ONLY WORKS ON DOCKERLESS INSTALLATIONS
#
# Install bid check and disk check on all your node servers
# You do not need to run nodewatch-bid-check.yml nor nodewatch-disk-check.yml if you run this
# 
# Settings to edit:
# All "bid_check" entries on OT-Settings/config.sh
# All "disk_check" entries on OT-Settings/config.sh
#
# This script will:
# 1. Delete existing OT-NodeWatch and OT-Settings directory
# 2. Clone OT-NodeWatch and OT-Settings git repositories back
# 3. Copy edited config
# 4. Delete any existing cron jobs for bid_check and disk_check
# 5. Add cron jobs for both with current configured values.

- name: Install Monitors
  hosts: otnodes
  vars_files: "/root/OT-Ansible-Files-and-Playbooks/hosts-config"
  gather_facts: no

  tasks:
    - name: Delete existing OT-NodeWatch folder
      file:
        path: /root/OT-NodeWatch
        state: absent

    - name: Delete existing OT-Settings folder
      file:
        path: /root/OT-Settings
        state: absent

    - name: Installing jq
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Clone OT-Settings git repository
      git:
        repo: 'https://github.com/calr0x/OT-Settings.git'
        dest: /root/OT-Settings
        force: yes

    - name: Install config.sh
      copy:
        src: ~/OT-Settings/config.sh
        dest: /root/OT-Settings/config.sh
        owner: root
        group: root
        mode: '0600'

    - name: Delete existing monitor (bid check) schedule from cron
      cron:
        name: Monitor Bid Check
        state: absent

    - name: Delete existing monitor (disk check) schedule from cron
      cron:
        name: Monitor Disk Check
        state: absent

    - name: Add monitor (bid check) schedule to cron (every hour)
      cron:
        name: Monitor Bid Check
        minute: '{{ bid_check_minute }}'
        hour: '{{ bid_check_hour }}'
        day: '{{ bid_check_day }}'
        month: '{{ bid_check_month }}'
        weekday: '{{ bid_check_weekday }}'
        job: "/root/OT-NodeWatch/bid_check.sh"

    - name: Add monitor (disk check) schedule to cron (every hour)
      cron:
        name: Monitor Disk Check
        minute: '{{ disk_check_minute }}'
        hour: '{{ disk_check_hour }}'
        day: '{{ disk_check_day }}'
        month: '{{ disk_check_month }}'
        weekday: '{{ disk_check_weekday }}'
        job: "/root/OT-NodeWatch/disk_check.sh"