---

- name: Uninstall ALL VERSION 1 projects
  hosts: all
  gather_facts: no

  tasks:
  - name: Delete /root/OT-Smoothbrain-Backup directory
    file:
      path: /root/OT-Smoothbrain-Backup
      state: absent

  - name: Delete /root/backup directory
    file:
      path: /root/backup
      state: absent

  - name: Delete /root/OT-DockSucker directory
    file:
      path: /root/OT-DockSucker
      state: absent

  - name: Delete /root/OT-NodeWatch directory
    file:
      path: /root/OT-NodeWatch
      state: absent

  - name: Delete /root/OT-Ansible-Files-and-Playbooks directory
    file:
      path: /root/OT-Ansible-Files-and-Playbooks
      state: absent

  - name: Delete existing Smoothbrain schedule from cron
    cron:
      name: "Restic backup"
      state: absent

  - name: Delete existing NodeWatch monitor (bid check) schedule from cron
    cron:
      name: Monitor Bid Check
      state: absent

  - name: Delete existing NodeWatch monitor (disk check) schedule from cron
    cron:
      name: Monitor Disk Check
      state: absent
