---

# This module will first prune the logs to a user-defined size and will limit future logs to that same size. Journalctl will auto delete beyond this size automatically.

- name: Limit journalctl log size to user-set value
  hosts: all
  gather_facts: no

  tasks:
    - name: Set limit of journalctl log
      replace:
        path: /etc/systemd/journald.conf
        regexp: '#?SystemMaxUse=.+'
        replace: SystemMaxUse='{{ set_log_size_limit }}'
    
    - name: Restart journalctl service
      service:
        name: systemd-journald
        state: restarted
